# Generated by Django 4.1.3 on 2022-12-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_vagas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
